version: "3"

networks:
  mongodb:
    external: true

services:
  main:
    image: ftn-info-platform:1.7.0
    build: .
    ports:
      - "8605:8605"
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
    networks:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 5s
